// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvbyuvcizjsxacjpwzge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Ynl1dmNpempzeGFjanB3emdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNTM2MDUsImV4cCI6MjA3NTkyOTYwNX0.BEgFxEbLFGu7n33xvG0QIulZZqq31dRGtHa-Vdi--Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});