// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbpdctiftkdxlgitudgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicGRjdGlmdGtkeGxnaXR1ZGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTU4MjQsImV4cCI6MjA3MjMzMTgyNH0.Nc-20VWhQOJCKKlzBxbH1CblEiczmWUE9L5tBUlwDo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});